# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Enter.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Enter(object):
    def setupUi(self, Dialog_Enter):
        Dialog_Enter.setObjectName("Dialog_Enter")
        Dialog_Enter.resize(422, 183)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_Enter.setWindowIcon(icon)
        Dialog_Enter.setStyleSheet("background-color: rgb(67, 67, 67);")
        Dialog_Enter.setModal(False)
        self.label = QtWidgets.QLabel(Dialog_Enter)
        self.label.setGeometry(QtCore.QRect(20, 40, 201, 31))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.lineEdit_for_pass = QtWidgets.QLineEdit(Dialog_Enter)
        self.lineEdit_for_pass.setGeometry(QtCore.QRect(20, 80, 371, 31))
        self.lineEdit_for_pass.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_for_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_for_pass.setObjectName("lineEdit_for_pass")
        self.pushButton_ok = QtWidgets.QPushButton(Dialog_Enter)
        self.pushButton_ok.setGeometry(QtCore.QRect(20, 130, 75, 23))
        self.pushButton_ok.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_ok.setAutoDefault(True)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog_Enter)
        self.pushButton_cancel.setGeometry(QtCore.QRect(110, 130, 75, 23))
        self.pushButton_cancel.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_cancel.setObjectName("pushButton_cancel")

        self.retranslateUi(Dialog_Enter)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Enter)

    def retranslateUi(self, Dialog_Enter):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Enter.setWindowTitle(_translate("Dialog_Enter", "Вход в программу"))
        self.label.setText(_translate("Dialog_Enter", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Введите пароль:</span></p></body></html>"))
        self.pushButton_ok.setText(_translate("Dialog_Enter", "Ок"))
        self.pushButton_cancel.setText(_translate("Dialog_Enter", "Отмена"))
import iconscryptor_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Enter = QtWidgets.QDialog()
    ui = Ui_Dialog_Enter()
    ui.setupUi(Dialog_Enter)
    Dialog_Enter.show()
    sys.exit(app.exec_())
