# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'save_img.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_save(object):
    def setupUi(self, Dialog_save):
        Dialog_save.setObjectName("Dialog_save")
        Dialog_save.resize(400, 134)
        Dialog_save.setMinimumSize(QtCore.QSize(400, 134))
        Dialog_save.setMaximumSize(QtCore.QSize(400, 134))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_save.setWindowIcon(icon)
        Dialog_save.setStyleSheet("background-image: url(:/background/icons/background.png);")
        Dialog_save.setModal(True)
        self.pushButton_save_yes = QtWidgets.QPushButton(Dialog_save)
        self.pushButton_save_yes.setGeometry(QtCore.QRect(110, 80, 71, 23))
        self.pushButton_save_yes.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_save_yes.setMaximumSize(QtCore.QSize(1000, 1000))
        self.pushButton_save_yes.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_save_yes.setObjectName("pushButton_save_yes")
        self.pushButton_save_no = QtWidgets.QPushButton(Dialog_save)
        self.pushButton_save_no.setGeometry(QtCore.QRect(190, 80, 71, 23))
        self.pushButton_save_no.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_save_no.setMaximumSize(QtCore.QSize(1000, 1000))
        self.pushButton_save_no.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_save_no.setObjectName("pushButton_save_no")
        self.label = QtWidgets.QLabel(Dialog_save)
        self.label.setGeometry(QtCore.QRect(50, 10, 281, 61))
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(1000, 1000))
        self.label.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")

        self.retranslateUi(Dialog_save)
        QtCore.QMetaObject.connectSlotsByName(Dialog_save)

    def retranslateUi(self, Dialog_save):
        _translate = QtCore.QCoreApplication.translate
        Dialog_save.setWindowTitle(_translate("Dialog_save", "Сохранение в галерею"))
        self.pushButton_save_yes.setText(_translate("Dialog_save", "Да"))
        self.pushButton_save_no.setText(_translate("Dialog_save", "Нет"))
        self.label.setText(_translate("Dialog_save", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Сохранить файл в галерее?</span></p></body></html>"))
import iconscryptor_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_save = QtWidgets.QDialog()
    ui = Ui_Dialog_save()
    ui.setupUi(Dialog_save)
    Dialog_save.show()
    sys.exit(app.exec_())
