# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'decode_sms.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Encode_Dialog(object):
    def setupUi(self, Encode_Dialog):
        Encode_Dialog.setObjectName("Encode_Dialog")
        Encode_Dialog.resize(874, 618)
        Encode_Dialog.setMinimumSize(QtCore.QSize(874, 618))
        Encode_Dialog.setMaximumSize(QtCore.QSize(874, 618))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/sms.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Encode_Dialog.setWindowIcon(icon)
        Encode_Dialog.setStyleSheet("background-image: url(:/background/icons/background.png);")
        self.plainTextEdit_for_mess_decode = QtWidgets.QPlainTextEdit(Encode_Dialog)
        self.plainTextEdit_for_mess_decode.setGeometry(QtCore.QRect(20, 230, 331, 371))
        self.plainTextEdit_for_mess_decode.setMinimumSize(QtCore.QSize(0, 0))
        self.plainTextEdit_for_mess_decode.setMaximumSize(QtCore.QSize(1000, 1000))
        self.plainTextEdit_for_mess_decode.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.plainTextEdit_for_mess_decode.setObjectName("plainTextEdit_for_mess_decode")
        self.label = QtWidgets.QLabel(Encode_Dialog)
        self.label.setGeometry(QtCore.QRect(20, 80, 531, 71))
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(1000, 1000))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Encode_Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 180, 541, 51))
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setMaximumSize(QtCore.QSize(1000, 1000))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Encode_Dialog)
        self.label_3.setGeometry(QtCore.QRect(570, -5, 281, 41))
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setMaximumSize(QtCore.QSize(1000, 1000))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.pushButton_accept_pass_decode = QtWidgets.QPushButton(Encode_Dialog)
        self.pushButton_accept_pass_decode.setGeometry(QtCore.QRect(360, 140, 121, 31))
        self.pushButton_accept_pass_decode.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_accept_pass_decode.setMaximumSize(QtCore.QSize(1000, 1000))
        self.pushButton_accept_pass_decode.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_accept_pass_decode.setObjectName("pushButton_accept_pass_decode")
        self.pushButton_open_decode = QtWidgets.QPushButton(Encode_Dialog)
        self.pushButton_open_decode.setGeometry(QtCore.QRect(380, 52, 81, 31))
        self.pushButton_open_decode.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_open_decode.setMaximumSize(QtCore.QSize(1000, 1000))
        self.pushButton_open_decode.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_open_decode.setObjectName("pushButton_open_decode")
        self.label_4 = QtWidgets.QLabel(Encode_Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 521, 41))
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_4.setMaximumSize(QtCore.QSize(1000, 1000))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.lineEdit_sys_messages_decode = QtWidgets.QTextEdit(Encode_Dialog)
        self.lineEdit_sys_messages_decode.setGeometry(QtCore.QRect(570, 30, 281, 71))
        self.lineEdit_sys_messages_decode.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_sys_messages_decode.setMaximumSize(QtCore.QSize(1000, 1000))
        self.lineEdit_sys_messages_decode.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_sys_messages_decode.setObjectName("lineEdit_sys_messages_decode")
        self.plainTextEdit_for_pass_decode = QtWidgets.QLineEdit(Encode_Dialog)
        self.plainTextEdit_for_pass_decode.setGeometry(QtCore.QRect(20, 140, 331, 31))
        self.plainTextEdit_for_pass_decode.setMinimumSize(QtCore.QSize(0, 0))
        self.plainTextEdit_for_pass_decode.setMaximumSize(QtCore.QSize(1000, 1000))
        self.plainTextEdit_for_pass_decode.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.plainTextEdit_for_pass_decode.setEchoMode(QtWidgets.QLineEdit.Password)
        self.plainTextEdit_for_pass_decode.setObjectName("plainTextEdit_for_pass_decode")
        self.lineEdit_path = QtWidgets.QLineEdit(Encode_Dialog)
        self.lineEdit_path.setGeometry(QtCore.QRect(20, 50, 351, 31))
        self.lineEdit_path.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_path.setMaximumSize(QtCore.QSize(1000, 1000))
        self.lineEdit_path.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.label_2.raise_()
        self.plainTextEdit_for_mess_decode.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.pushButton_accept_pass_decode.raise_()
        self.pushButton_open_decode.raise_()
        self.label_4.raise_()
        self.lineEdit_sys_messages_decode.raise_()
        self.plainTextEdit_for_pass_decode.raise_()
        self.lineEdit_path.raise_()

        self.retranslateUi(Encode_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Encode_Dialog)

    def retranslateUi(self, Encode_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Encode_Dialog.setWindowTitle(_translate("Encode_Dialog", "Декодер Сообщения"))
        self.label.setText(_translate("Encode_Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Введите пароль для дешифрования:</span></p></body></html>"))
        self.label_2.setText(_translate("Encode_Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Ваше расшифрованное сообщение:</span></p></body></html>"))
        self.label_3.setText(_translate("Encode_Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">System Messages:</span></p></body></html>"))
        self.pushButton_accept_pass_decode.setText(_translate("Encode_Dialog", "Подтвердить"))
        self.pushButton_open_decode.setText(_translate("Encode_Dialog", "Открыть"))
        self.label_4.setText(_translate("Encode_Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; font-style:italic;\">txt файл с зашифрованным смс:</span></p></body></html>"))
import iconscryptor_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Encode_Dialog = QtWidgets.QDialog()
    ui = Ui_Encode_Dialog()
    ui.setupUi(Encode_Dialog)
    Encode_Dialog.show()
    sys.exit(app.exec_())
