# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'send_sms.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_send(object):
    def setupUi(self, Dialog_send):
        Dialog_send.setObjectName("Dialog_send")
        Dialog_send.resize(923, 526)
        Dialog_send.setMinimumSize(QtCore.QSize(923, 526))
        Dialog_send.setMaximumSize(QtCore.QSize(923, 526))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/email.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_send.setWindowIcon(icon)
        Dialog_send.setStyleSheet("background-image: url(:/background/icons/background.png);")
        self.label = QtWidgets.QLabel(Dialog_send)
        self.label.setGeometry(QtCore.QRect(20, 10, 371, 51))
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(1000, 1000))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.plainTextEdit_send_from = QtWidgets.QPlainTextEdit(Dialog_send)
        self.plainTextEdit_send_from.setGeometry(QtCore.QRect(20, 70, 381, 31))
        self.plainTextEdit_send_from.setMinimumSize(QtCore.QSize(0, 0))
        self.plainTextEdit_send_from.setMaximumSize(QtCore.QSize(1000, 1000))
        self.plainTextEdit_send_from.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.plainTextEdit_send_from.setObjectName("plainTextEdit_send_from")
        self.label_2 = QtWidgets.QLabel(Dialog_send)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 571, 41))
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setMaximumSize(QtCore.QSize(1000, 1000))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog_send)
        self.label_3.setGeometry(QtCore.QRect(20, 240, 581, 41))
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setMaximumSize(QtCore.QSize(1000, 1000))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.plainTextEdit_send_to = QtWidgets.QPlainTextEdit(Dialog_send)
        self.plainTextEdit_send_to.setGeometry(QtCore.QRect(20, 290, 381, 31))
        self.plainTextEdit_send_to.setMinimumSize(QtCore.QSize(0, 0))
        self.plainTextEdit_send_to.setMaximumSize(QtCore.QSize(1000, 1000))
        self.plainTextEdit_send_to.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.plainTextEdit_send_to.setObjectName("plainTextEdit_send_to")
        self.label_4 = QtWidgets.QLabel(Dialog_send)
        self.label_4.setGeometry(QtCore.QRect(630, 0, 251, 31))
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_4.setMaximumSize(QtCore.QSize(1000, 1000))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.pushButton_send = QtWidgets.QPushButton(Dialog_send)
        self.pushButton_send.setGeometry(QtCore.QRect(20, 480, 91, 31))
        self.pushButton_send.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_send.setMaximumSize(QtCore.QSize(1000, 1000))
        self.pushButton_send.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_send.setObjectName("pushButton_send")
        self.checkBox_sms = QtWidgets.QCheckBox(Dialog_send)
        self.checkBox_sms.setGeometry(QtCore.QRect(20, 390, 391, 21))
        self.checkBox_sms.setMinimumSize(QtCore.QSize(0, 0))
        self.checkBox_sms.setMaximumSize(QtCore.QSize(1000, 1000))
        self.checkBox_sms.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.checkBox_sms.setObjectName("checkBox_sms")
        self.checkBox_img = QtWidgets.QCheckBox(Dialog_send)
        self.checkBox_img.setGeometry(QtCore.QRect(20, 410, 391, 21))
        self.checkBox_img.setMinimumSize(QtCore.QSize(0, 0))
        self.checkBox_img.setMaximumSize(QtCore.QSize(1000, 1000))
        self.checkBox_img.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.checkBox_img.setObjectName("checkBox_img")
        self.checkBox_both = QtWidgets.QCheckBox(Dialog_send)
        self.checkBox_both.setGeometry(QtCore.QRect(20, 450, 391, 21))
        self.checkBox_both.setMinimumSize(QtCore.QSize(0, 0))
        self.checkBox_both.setMaximumSize(QtCore.QSize(1000, 1000))
        self.checkBox_both.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.checkBox_both.setObjectName("checkBox_both")
        self.label_5 = QtWidgets.QLabel(Dialog_send)
        self.label_5.setGeometry(QtCore.QRect(20, 330, 591, 41))
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setMaximumSize(QtCore.QSize(1000, 1000))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.lineEdit_system_message_send = QtWidgets.QTextEdit(Dialog_send)
        self.lineEdit_system_message_send.setGeometry(QtCore.QRect(630, 30, 261, 71))
        self.lineEdit_system_message_send.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_system_message_send.setMaximumSize(QtCore.QSize(1000, 1000))
        self.lineEdit_system_message_send.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 8pt \"MS Shell Dlg 2\";")
        self.lineEdit_system_message_send.setObjectName("lineEdit_system_message_send")
        self.plainTextEdit_send_pass = QtWidgets.QLineEdit(Dialog_send)
        self.plainTextEdit_send_pass.setGeometry(QtCore.QRect(20, 160, 381, 31))
        self.plainTextEdit_send_pass.setMinimumSize(QtCore.QSize(0, 0))
        self.plainTextEdit_send_pass.setMaximumSize(QtCore.QSize(1000, 1000))
        self.plainTextEdit_send_pass.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.plainTextEdit_send_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.plainTextEdit_send_pass.setObjectName("plainTextEdit_send_pass")
        self.checkBox_video = QtWidgets.QCheckBox(Dialog_send)
        self.checkBox_video.setGeometry(QtCore.QRect(20, 430, 391, 21))
        self.checkBox_video.setMinimumSize(QtCore.QSize(0, 0))
        self.checkBox_video.setMaximumSize(QtCore.QSize(1000, 1000))
        self.checkBox_video.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.checkBox_video.setObjectName("checkBox_video")
        self.pushButton_auto_fill = QtWidgets.QPushButton(Dialog_send)
        self.pushButton_auto_fill.setGeometry(QtCore.QRect(410, 20, 111, 31))
        self.pushButton_auto_fill.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_auto_fill.setMaximumSize(QtCore.QSize(1000, 1000))
        self.pushButton_auto_fill.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_auto_fill.setObjectName("pushButton_auto_fill")

        self.retranslateUi(Dialog_send)
        QtCore.QMetaObject.connectSlotsByName(Dialog_send)

    def retranslateUi(self, Dialog_send):
        _translate = QtCore.QCoreApplication.translate
        Dialog_send.setWindowTitle(_translate("Dialog_send", "Отправка сообщения"))
        self.label.setText(_translate("Dialog_send", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Введите свой адрес электронной почты:</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog_send", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Введите пароль от электронной почты:</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog_send", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Введите адрес получателя:</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog_send", "<html><head/><body><p><span style=\" font-size:10pt;\">System Messages:</span></p></body></html>"))
        self.pushButton_send.setText(_translate("Dialog_send", "Отправить"))
        self.checkBox_sms.setText(_translate("Dialog_send", "Сообщение"))
        self.checkBox_img.setText(_translate("Dialog_send", "Изображение"))
        self.checkBox_both.setText(_translate("Dialog_send", "Все файлы"))
        self.label_5.setText(_translate("Dialog_send", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Выберите опцию:</span></p></body></html>"))
        self.checkBox_video.setText(_translate("Dialog_send", "Видео"))
        self.pushButton_auto_fill.setText(_translate("Dialog_send", "Автозаполнение"))
import iconscryptor_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_send = QtWidgets.QDialog()
    ui = Ui_Dialog_send()
    ui.setupUi(Dialog_send)
    Dialog_send.show()
    sys.exit(app.exec_())
